### PR TITLE
Hw2

### PR DESCRIPTION
**Pull request by farfro**
What I did: 
completed flex box froggy, grid garden, finding and highlighting word, change background on interval and created a form that print to console on submit.

I completed all the requirements to my best abilities. I am looking for feedback, let me know if there is anything I should fix. I couldn't find the background color for the word highlighting page in bootstrap. Let me know how you got around that.

### CODE REVIEW

**Comment by lee-112** [comment]
Hey @farfro,

I've reviewed your code and am pleased to report that it functions as intended.

** **Here are a few suggestions to fix/improve code:** **

1\. `count.html` has a WAVE label error. To fix this issue:
* Add `for="word"` to the `<label>` tag.
* Add `type="text"` to the `<input>` tag.
<br>

2\. `background.js` code runs without pressing the input button. To fix this issue:
* Change `let time = setColor(3000);` to `let time;`.
<br>

3\. `form.html` has no validation checks allowing form empty form submissions. To fix this issue:
* Add `required` to the form `<input>` tags. 

4\. Set a `max-width` instead of `width`:
* This will make page content responsive and readable on smaller screens and mobile devices.
<br>

Overall, good work! Your code is well-written, formatted, and organized.

**Comment by gsampang** [comment]
Well done. I ran your code on my system and found it works mostly as expected. 
As for “the background color for the word highlighting page in bootstrap” I couldn’t find that one either. I got around this by using the style attribute instead of using bootstrap.
Regarding 04 - Background, I found that it would change background color even before I hit start. Is this intentional?
Overall though good job :)

**Comment by farfro** [comment]
> Well done. I ran your code on my system and found it works mostly as expected.
> As for “the background color for the word highlighting page in bootstrap” I couldn’t find that one either. I got around this by using the style attribute instead of using bootstrap.
> Regarding 04 - Background, I found that it would change background color even before I hit start. Is this intentional?
> Overall though good job :)

Thank you, that was helpful. As for the background color, I assumed we should start with a background color that changes every 3 seconds.

**Comment by farfro** [comment]
> Hey @farfro,
> 
> I've reviewed your code and am pleased to report that it functions as intended.
> 
> ** **Here are a few suggestions to fix/improve code:** **
> 
> 1. `count.html` has a WAVE label error. To fix this issue:
> 
> * Add `for="word"` to the `<label>` tag.
> * Add `type="text"` to the `<input>` tag.
> 
> 
> 2. `background.js` code runs without pressing the input button. To fix this issue:
> 
> * Change `let time = setColor(3000);` to `let time;`.
> 
> 
> 3. `form.html` has no validation checks allowing form empty form submissions. To fix this issue:
> 
> * Add `required` to the form `<input>` tags.
> 
> 4. Set a `max-width` instead of `width`:
> 
> * This will make page content responsive and readable on smaller screens and mobile devices.
> 
> 
> Overall, good work! Your code is well-written, formatted, and organized.

Good catch Lee, I didn't notice those attributes were missing. I tried adding the max-width class from bootstrap, wouldn't work.

**Pull request merged**
