### PR TITLE
completed

### PR DESCRIPTION
**Pull request by farfro**
1. I used the Thrones api to display information of each character.
2. i created a chart using the api and chart.js
3. created a react app that has 3 routes that lead to home, search and houses
 home is the landing page, while the search page is where you can search for a character and finally the houses page shows a chart that shows character that belong to a particular house.

let me know if you have any suggestion

### CODE REVIEW

**Comment by gsampang** [comment]
Well done. I ran your code on my system and found it works mostly as expected.
I will focus my feedback on part 1 and 2 since these are the parts I understand the most.

Regarding 1:
- I was surprised by the way the display is implemented. I was expecting the use of grid since that’s how I’ve seen this done before, but was pleasantly surprised to see how well it worked with flex. No suggestions on better implementation there.

Regarding 2:
- No suggestions, your implementation already looks simpler and easier to understand than the implementation I went with. Props to you.

Overall, well done.

**Review by gsampang — COMMENTED** [review]
Well done. I ran your code on my system and found it works mostly as expected.
I will focus my feedback on part 1 and 2 since these are the parts I understand the most.

Regarding 1:
- I was surprised by the way the display is implemented. I was expecting the use of grid since that’s how I’ve seen this done before, but was pleasantly surprised to see how well it worked with flex. No suggestions on better implementation there.

Regarding 2:
- No suggestions, your implementation already looks simpler and easier to understand than the implementation I went with. Props to you.

Overall, well done.

**Review by gsampang — COMMENTED** [review]
Well done. I ran your code on my system and found it works mostly as expected.
I will focus my feedback on part 1 and 2 since these are the parts I understand the most.

Regarding 1:
- I was surprised by the way the display is implemented. I was expecting the use of grid since that’s how I’ve seen this done before, but was pleasantly surprised to see how well it worked with flex. No suggestions on better implementation there.

Regarding 2:
- No suggestions, your implementation already looks simpler and easier to understand than the implementation I went with. Props to you.

Overall, well done.

**Comment by anhoop89** [comment]
**01-character:** 
- Everything runs properly as expected from the requirements and screenshot.
- There is warning alerts from WAVE. You need to add an alt for those API photos. 
image
**02-chart:** 
- Groups and the chart display look good. 
- The title should be bold and included in the chart container. 
- Minor style: The container of the chart needs to be centered on the page. It means both the left and right side has some space instead of a full-width atm. That's what the given screenshot shows. 
**03-React**
- Home: looks good
- Search: It can search for a character and shows up its photo. Wave issues
image
- Houses: looks nice! One warning alert - you just need to remove it in your html file as i did to solve it. 
image

Great job! I like it.

**Comment by farfro** [comment]
I fixed most of the wave issues you've mentioned. Thanks for the review.

**Pull request merged**
