### PR TITLE
completed

### PR DESCRIPTION
**Pull request by farfro**
made changes to the palindrome.html and palindrome.js

### CODE REVIEW

**Comment by gsampang** [comment]
Well done! I ran your code on my system and found it worked exactly as expected. I ran an accessibility check with WAVE and found there were no errors of any kind, not even warnings. Overall good job :)

**Comment by gsampang** [comment]
Upon further consideration I did find one minor thing you could change. I notice you put the Exercise 2 box at the center of the page, and based on the HW1 reference pictures I believe it goes at the top of the page with a slight margin from the top.

**Comment by anhoop89** [comment]
So far you did a great job! 
I pulled your code and ran. it worked properly overall as expected. 

There is some minor issues: 
Wave: 1 Contrast Errors
1 X Very low contrast
Very low contrast 1More information
This error will not show up until you enter a number and run WAVE. I got this issue. I fixed by increasing the font size. 

Usually the instructor expected our site should be the same as the screenshot as possible. I don't know if you moved everything in the center of the page, that would impact your grade or not. Please reach out to TA if needed.

**Comment by farfro** [comment]
Wave is not showing me the contrast issue on my end.

**Pull request merged**
